applications/emplois/urls.py
# -*- coding: utf-8 -*
from django.conf.urls import url, include

from . import views
from django.views import generic
from django.views.decorators.cache import cache_page
__author__ = 'Guinsly'

app_name = 'emplois'
urlpatterns = [
      #url(r'^$', views.hello, name='index'),
      url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
      url(r'^stats$', views.StatsView.as_view(), name='stats'),
      url(r'^searchJobs/$', cache_page(60 * 15)(views.job_search), name='job_search'),
      url(r'^stats_emplois/$', views.emplois, name='emplois'),
      url(r'^about$', views.AboutView.as_view(), name='about'),
      url(r'^all_jobs_posted$', views.AllJobsView.as_view(), name='all_jobs_posted'),
      url(r'^expiring$', views.ExpiringSoonView.as_view(), name='expire'),
      url(r'^latest$', views.LatestView.as_view(), name='latest'),
      url(r'^i18n/', include('django.conf.urls.i18n')),
      url(r'^update/$', views.update_and_tweets, name='upgrade'),
      url(r'^download/$', views.download, name='download'),
      url(r'^jobs/$', views.IndexView.as_view(), name='index'),
      url(r'^$', views.IndexView.as_view(), name='index'),

        ]

cityjobs/urls.py
from django.conf import settings
from django.conf.urls import url, include, handler404, handler500
from django.contrib import admin
from django.conf.urls.static import static
admin.autodiscover()

#from applications.cityjobs.views import *

urlpatterns = [
    url(r'^emplois/', include('applications.emplois.urls', namespace="emplois")),
    url(r'^ottawacityjobs/', include('applications.emplois.urls')),
    #url(r'^admin/', admin.site.urls),
    # i18n
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^', include('applications.emplois.urls')),
    url(r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_ROOT, 'show_indexes': False}),
]# + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

handler404 = 'applications.emplois.views.handler404'
handler500 = 'applications.emplois.views.handler500'

ottawacityjobs/urls.py
from django.conf import settings
from django.conf.urls import url, include, handler404, handler500
from django.contrib import admin
from django.conf.urls.static import static
admin.autodiscover()

#from applications.cityjobs.views import *

urlpatterns = [
    url(r'^jobs/', all_jobs),
    #url(r'^desc/', all_descriptions),
    url(r'^emplois/', include('applications.emplois.urls', namespace="emplois")),
    url(r'^ottawacityjobs/', include('applications.emplois.urls')),
    url(r'^admin/', admin.site.urls),
    # i18n
    url(r'^i18n/', include('django.conf.urls.i18n')),
    #url (r'^settings', include('metasettings.urls')),
    #url(r'^searchBlog/$','emplois.views.SearchJobView',name="blog_search"),
    url(r'^', include('applications.emplois.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

handler404 = 'applications.emplois.views.handler404'
handler500 = 'applications.emplois.views.handler500'

applications/emplois/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.utils.encoding import python_2_unicode_compatible

import datetime
from django.utils import timezone

# Create your models here.
@python_2_unicode_compatible
class Job(models.Model):
    '''
    Job.models
    '''
    FRENCH = 'FR'
    ENGLISH = 'EN'
    LANGUAGE_CHOICE = (
            (FRENCH, 'Francais'),
            (ENGLISH, 'English'),
            )
    def __str__(self):
        return self.POSITION
    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=7) <= self.POSTDATE <= now
    def still_not_expired_job_list(self):
        now = timezone.now()
        return self.EXPIRYDATE >= now


    JOBURL = models.URLField(max_length=250, blank=True, null=True)
    EXPIRYDATE = models.DateField(auto_now=False, blank=True, null=True)
    SALARYMAX = models.CharField(max_length=40, blank=True, null=True)
    SALARYMIN = models.CharField(max_length=40, blank=True, null=True)
    SALARYTYPE = models.CharField(max_length=20, blank=True, null=True)
    NAME = models.CharField(max_length=40, blank=True, null=True)
    language = models.CharField(max_length=2, choices=LANGUAGE_CHOICE, default=ENGLISH)
    POSITION = models.CharField(max_length=150, blank=True, null=True)
    JOBREF = models.CharField(max_length=30, unique=True, blank=True, null=True)
    JOB_SUMMARY = models.TextField(blank=True, null=True)
    POSTDATE = models.DateTimeField(auto_now=False, blank=True, null=True)
    slug = models.CharField(max_length=200)
    tweeted = models.BooleanField(default=False)

@python_2_unicode_compatible
class Description(models.Model):
    '''
    Job.Description.models
    '''
    def __str__(self):
        return self.COMPANY_DESC

    jobs = models.ForeignKey(Job, on_delete=models.CASCADE)
    KNOWLEDGE = models.TextField(blank=True, null=True)
    LANGUAGE_CERTIFICATES = models.TextField(blank=True, null=True)
    EDUCATIONANDEXP = models.TextField(blank=True, null=True)
    COMPANY_DESC = models.TextField(blank=True, null=True)
    POSTDATE = models.DateTimeField(auto_now=True, blank=True, null=True)

applications/emplois/views.py
# -*- coding: utf-8 -*-
#Django
from django.shortcuts import render, get_object_or_404, redirect
from django.views import generic
from django.utils import timezone
from django.core import serializers
from django.core.urlresolvers import reverse
from django.http import HttpResponse
from django.conf import settings
#pagination
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
#Task queues
#cache
from django.views.decorators.cache import cache_page
#models and utils
from .models import Job, Description
#from .utils import job_object_list, language_set
# Standard Python module
from json import dumps, loads
from datetime import datetime, timedelta
# Create your views here.

from django.http import HttpResponseRedirect
from .utils import process_it

import logging
logger = logging.getLogger(__name__)

def language_set(language):
    if "-" in language:
        return (language.split('-')[1]).upper()
    else:
        return language.upper()

def hello(request):
  return HttpResponse('<h1>Hello world emplois 2</h1>')


#http:://localhost:8001/
class IndexView(generic.ListView):
    """
    this is the ROOT page
    return a list of Jobs
    """
    template_name='emplois/index.html'
    context_object_name='latest_jobs_list'
    paginate_by = 10

    def language(self):
        """Return the user default language"""
        language = language_set(self.request.LANGUAGE_CODE)
        language = language.upper()
        return language

    def get_queryset(self):
        """
        Return a list of Jobs that have an EXPIRATION DATE
        greater than Now() and a default Language
        """
        #import ipdb;ipdb.set_trace()
        return Job.objects.filter(language=self.language(),\
              EXPIRYDATE__gt=datetime.now())\
            .order_by('EXPIRYDATE')


#http://localhost:8001/emplois/latest
class LatestView(generic.ListView):
    """Retrieve the latest jobs that Ottawa had
    published these past 2 weeks
    """
    template_name='emplois/index.html'
    paginate_by = 10
    context_object_name='latest_jobs_list'

    def language(self):
        """Return the user default language"""
        language = language_set(self.request.LANGUAGE_CODE)
        return language

    def get_queryset(self):
        """
        Return a list of Jobs that has a PUBLICATION DATE
        within the past 2 weeks

        Order: by PUBLICATION DATE
        """
        return Job.objects.filter(language=self.language(),
        POSTDATE__gte=datetime.now()-timedelta(days=14)).order_by('-POSTDATE')


#http://localhost:8001/emplois/expiring
class ExpiringSoonView(generic.ListView):
    """
    return a list of Jobs that will expire within the next two weeks
    """
    template_name='emplois/index.html'
    paginate_by = 10
    context_object_name='latest_jobs_list'

    def language(self):
        """Return the user default language"""
        language = language_set(self.request.LANGUAGE_CODE)
        return language

    def get_queryset(self):
        """
        Return a list of jobs
        that expires within today's Date and 2 weeks
        from now

        Order_by = Expiration Date
        """
        today =  timezone.now().date()
        ending_in_two_weeks = datetime.now()+timedelta(days=14)
        return Job.objects.filter(language=self.language(),
         EXPIRYDATE__lte=ending_in_two_weeks,EXPIRYDATE__gte=today)\
                 .order_by('EXPIRYDATE')

#http://localhost:8001/emplois/all_job_posted
class AllJobsView(generic.ListView):
    """
    Return all Jobs that are in the Database
    """
    template_name='emplois/index.html'
    paginate_by = 10
    context_object_name='latest_jobs_list'

    def language(self):
        """Return the user default language"""
        language = language_set(self.request.LANGUAGE_CODE)
        return language

    def get_queryset(self):
        """Return all the Jobs

        order by: PUBLICATION DATE
        latest is at the end
        """
        return Job.objects.filter(language=self.language()).order_by('POSTDATE')

#http://localhost:8001/emplois/<id>
class DetailView(generic.DetailView):
    """
    Return the detail content of a job

    NOTES???: The language is set by default
    """
    model = Job
    paginate_by = 10
    template_name = 'emplois/details.html'
    context_object_name='job'

#http://localhost:8001/emplois/stats
class StatsView(generic.TemplateView):
    """
    Return a list of aggratated timestamps that will populate
    the Javascript array in order to make the
    Calendar HeatMap view
    """
    template_name='emplois/stats.html'

    def language(self):
        """Return the user default language"""
        language = language_set(self.request.LANGUAGE_CODE)
        return language

    def get_context_data(self, **kwargs):
        """
        Return a list of Job's date
        """
        import time
        from django.db.models import Count
        #
        context = super(StatsView, self).get_context_data(**kwargs)
        #get all the English/French values
        english = Job.objects.filter(language=self.language())
        #Grouup by date
        data = english.values('POSTDATE').annotate(dcount=Count('POSTDATE'))
        content = {}
        #I want the date in a UNIX TIME format
        for job in data:
            unix_time = time.mktime(job['POSTDATE'].timetuple())
            content.update({unix_time:job['dcount']})
        context['stats'] = content

        return context

#http://localhost:8001/emplois/about
class AboutView(generic.TemplateView):
    """Retuns a static page that
    will show why do I create this website
    """
    template_name='emplois/about.html'
    context_object_name='language'

    def get_context_data(self, **kwargs):
        """
        Returns the language value
        """
        context = super(AboutView, self).get_context_data(**kwargs)
        context['language'] = language_set(self.request.LANGUAGE_CODE)

        return context

#http://localhost:8001/emplois/searchJobs/<searchKey>
#@cache_page(60 * 1, key_prefix="site1"  )
def job_search(request):
    """
    This function will receive a query
    from the Search Box and will return a list of
    jobs from that query
    """
    if 'searchKey' in request.GET:
        keyword = request.GET['searchKey']
        if not keyword :
                return redirect('/')
        else:
            lang = language_set(request.LANGUAGE_CODE)
            latest_jobs_list = Job.objects.filter(POSITION__icontains\
                    = keyword,language__icontains=lang).\
                    order_by('-POSTDATE')
            paginator = Paginator(latest_jobs_list, 10)
            page = request.GET.get('page')
            try:
                latest_jobs_list = paginator.page(page)
            except PageNotAnInteger:
                # If page is not an integer, deliver first page.
                latest_jobs_list = paginator.page(1)
            except EmptyPage:
                # If page is out of range (e.g. 9999), deliver last page of results.
                latest_jobs_list = paginator.page(paginator.num_pages)
            return render(request,'emplois/result.html',{'latest_jobs_list':latest_jobs_list})
    return redirect('/')

##########JAVASCRIPT = JSOM ##########
#http://localhost:8001/emplois/<annee>/<mois>/<jour>
def emplois(request):
    """
    This will receive an AJAX request and will return a JSON
    object
    """
    import datetime
    jobs = Job.objects.filter(
        POSTDATE__year=request.GET.get('annee'),
        POSTDATE__month=request.GET.get('mois'),
        POSTDATE__day=request.GET.get('jour'),
        language=language_set(request.LANGUAGE_CODE)
        )
    #logger.info('Annee : ' + request.GET.get('annee') )
    #logger.info('Mois : ' + request.GET.get('mois'))
    #logger.info('Jour : ' + request.GET.get('jour'))
    #logger.info('Language Code : ' + request.LANGUAGE_CODE)
    data = serializers.serialize('json', jobs)
    return HttpResponse(data, content_type='application/json')

#http://localhost:8001/emplois/download
def download(request):
    """
    This will return all the Job objects form the DB
    in JSON
    """
    import datetime
    data = serializers.serialize('json', Job.objects.all() )
    data = dumps(loads(data), indent=4)
    return HttpResponse(data, content_type='application/json')



def update_and_tweets(request):
    """
    This will update or tweet
    depending on the time
    """
    logger.info('Updating the list of jobs')
    from datetime import datetime, timedelta, time
    from pytz import timezone

    ottawa_timezone = timezone('America/Montreal')
    ottawa_now = datetime.now(ottawa_timezone)
    now_time = ottawa_now.time()
    #tweet_time = False#now_time >= time(5,30) and now_time <= time(18,30)
    upgrade_time = True# now_time >= time(17,00) and now_time <= time(19,30)

    if upgrade_time:
        res = process_it()
        #Update the list of jobs from Open Data portal (Ottawa.open.data)
        logger.info('yes we added new jobs')
        return redirect("/")
    else:
        logger.info("no we didn't have new jobs in full.jsonr")
        return redirect("/")


#Error on this template
#I try  to create a Class based view of 'def job_search()'
class SearchJobView(generic.ListView):
    """
    An attempt to use a Class Based view to
    process the job search
    """
    template_name='emplois/index.html'
    context_object_name='latest_jobs_list'

    def get(self, request, *args, **kwargs):
        response = super(self, SearchJobView).get(request, *args, **kwargs)
        keyword = kwargs.get('searchKey')
        if keyword:
            return Job.objects.filter(POSITION__icontains = keyword).order_by('-POSTDATE')
        else:
            return redirect('/')

def handler404(request):
    response = render(request, 'emplois/page_not_found.html')
    logger.info('Error page not found 404')
    response.status_code = 404

applications/emplois/templates/emplois/about.html
{% extends "base.html" %}
{% load humanize %}

	{% block content %}

{% if language == "EN" %}


		<h1>About page</h1>

	 <p>This website provides the current and past job opportunities at the  <a href="http://ottawa.ca/en/city-hall/jobs-city" target="_blank">City of Ottawa</a>. The data obtained comes directly from the <a href="http://data.ottawa.ca/en/dataset/job-opportunities" target="_blank">Ottawa Open data portal</a>.</p>

	<p>The content of this website is under the <a target="_blank" href="https://creativecommons.org/licenses/by-nd/3.0/">CC-BY-ND</a> license. The images of the Ottawa city flags is under the Wiki Creative Commons License. The code for this application is also available on <a href="https://github.com/guinslym/django-ottawa-city-jobs" target="_blank">Github</a>. Some third party of the code can't be transfert like the Twitter bot api and the bitly api.</p>

	{% endif %}



{% if language == "FR" %}


		<h1>À Propos</h1>

	 <p>Cette page web fournit la plus récente <a href="http://ottawa.ca/fr/hotel-de-ville/emplois-la-ville" target="_blank">liste d'emplois à Ville d'Ottawa</a>. Les emplois qui ne sont plus affichés sur le site web de la ville parce qu'ils ont été expirés, sont aussi accessible sur ce site. Les données ont été récupérés sur <a href="http://data.ottawa.ca/fr/dataset/job-opportunities" target="_blank">le portail de données ouvertes d'Ottawa</a></p>

	 <p>Le contenu de ce site web est sous license <a target="_blank" href="https://creativecommons.org/licenses/by-nd/3.0/">CC-BY-ND</a>. L'image du drapeau de la ville d'Ottawa est sous license Wiki Creative Commons. Les scripts qui ont permis de créer cette application web sont aussi disponible sur <a href="https://github.com/guinslym/django-ottawa-city-jobs" target="_blank">Github</a> sous license CC-BY. Les scripts contenants des informations personnelles par exemple pour faire fonctionner la publication de Tweet sur Twitter n'ont pas été inclus dans le code sur <a href="https://github.com/guinslym/django-ottawa-city-jobs" target="_blank">Github</a></p>

	{% endif %}
{% endblock %}

applications/emplois/templates/emplois/app_error_500.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>404 error</title>
  </head>
  <body>
    <h1>Page not found custom -- 500</h1>
  </body>
</html>

applications/emplois/templates/emplois/details.html
{% extends "base.html" %}
{% load i18n %}
{% load humanize %}



	{% block content %}

	<div class="row">
		<div class="col-lg-12">
			<h1>{{ job.POSITION }}</h1>

				<ul>
{% get_language_info for LANGUAGE_CODE as lang %}

{% if lang.code == 'fr' %}
					<li><strong>Salary Max: </strong>
						{% if ',' in job.SALARYMAX %}
					{{ job.SALARYMAX | intcomma }} $
					{% else %}
					{{ job.SALARYMAX | floatformat:2 }} $
					{% endif %}
					</li>
					<li><strong>Salary Min: </strong>
						{% if ',' in job.SALARYMIN %}
					{{ job.SALARYMIN | intcomma }} $
					{% else %}
					{{ job.SALARYMIN | floatformat:2 }} $
					{% endif %}
					</li>
{% else %}
					<li><strong>Salary Max: </strong>
						{% if ',' in job.SALARYMAX %}
					$ {{ job.SALARYMAX | intcomma }}
					{% else %}
					$ {{ job.SALARYMAX | floatformat:2 }}
					{% endif %}
					</li>
					<li><strong>Salary Min: </strong>
						{% if ',' in job.SALARYMIN %}
					$ {{ job.SALARYMIN | intcomma }}
					{% else %}
					$ {{ job.SALARYMIN | floatformat:2 }}
{% endif %}
</li>



{% endif %}

					<li><strong>Expiring date: </strong>{{ job.EXPIRYDATE }}</li>
					<li><strong>postdate: </strong> {{ job.POSTDATE| naturalday }}</li>
					<li><strong>apply link: </strong> <a href="{{ job.JOBURL }}" target="_blank">apply</a></li>
			</ul>

			{% autoescape off %}
				{{job.job_summary}}
				{{job.description_set.all.0.KNOWLEDGE }}
				{{job.description_set.all.0.EDUCATIONANDEXP }}
				{{job.description_set.all.0.LANGUAGECERT }}
				{{job.description_set.all.0.COMPANY_DESC }}
			{% endautoescape %}

		</div>
	</div>

<div class="row text-center">
	<h3><a href="/">Home page</a></h3>
</div>


	{% endblock %}


<script type="text/javascript">
	$(function() {
	   $("br").remove();
	});
</script>

applications/emplois/templates/emplois/index.html
{% extends "base.html" %}
{% load bootstrap_pagination %}
{% load i18n %}
{% load humanize %}


	{% block content %}

	<h1>{% trans "Job list"%} </h1>

	<div class="row text-right">
		<ul>
			<li><strong>{% trans "Sort by"%}:</strong></li>
			<li><a href="{% url 'emplois:latest' %}">{% trans "Posted within the last 2 weeks"%}</a></li>
			<li><a href="{% url 'emplois:expire' %}">{% trans "Will expired in 2 weeks from now" %}</a></li>
			<li><a href="{% url 'emplois:all_jobs_posted' %}">{% trans "All jobs" %}</a></li>
		</ul>
	</div>

<div class="row">
<div class="text-left">
<br/>
<!--
                       _             __  _
    ____  ____ _____ _(_)___  ____ _/ /_(_)___  ____
   / __ \/ __ `/ __ `/ / __ \/ __ `/ __/ / __ \/ __ \
  / /_/ / /_/ / /_/ / / / / / /_/ / /_/ / /_/ / / / /
 / .___/\__,_/\__, /_/_/ /_/\__,_/\__/_/\____/_/ /_/
/_/          /____/
-->
 {% bootstrap_paginate page_obj last_label="Last" first_label="First"  range=5 show_prev_next='true' previous_label="<" next_label=">" %}
 <!-- pagination -->
</div>

</div>

{#% load cache %#}
{#% cache 500 sidebar %#}

<div class="outterspace">

<span class="nonetype" style="display:none;">
	{{ latest_jobs_list }}
</span>
	{% for emploi in latest_jobs_list %}
	<div class="filterWrap">

		<h3><a href="{% url 'emplois:detail' emploi.id %}">{{ emploi.POSITION }}.</a></h3>

		<p>
     	{% autoescape off %}
			      {{ emploi.JOB_SUMMARY |truncatewords_html:50}}
			{% endautoescape %}
		</p>
		<ul>

		{% get_language_info for LANGUAGE_CODE as lang %}
		{% if lang.code == 'fr' %}
			<li><strong>{% trans "Salary" %}: </strong>
				{% if ',' in emploi.SALARYMAX %}
			{{ emploi.SALARYMAX | intcomma }} $
			{% else %}
			{{ emploi.SALARYMAX | floatformat:2 }} $
			{% endif %}
			</li>
		{% else %}
			<li><strong>{% trans "Salary" %}: </strong>
				{% if ',' in emploi.SALARYMAX %}
			$ {{ emploi.SALARYMAX | intcomma }}
			{% else %}
			$ {{ emploi.SALARYMAX | floatformat:2 }}
			{% endif %}
			</li>
		{% endif %}


			<li><strong>{% trans "Expiring date"%} : </strong>{{ emploi.EXPIRYDATE }}</li>
			<li><strong>{% trans "postdate" %}: </strong> {{ emploi.POSTDATE| naturalday }}</li>
			<li><strong>{% trans "Apply link" %}: </strong> <a href="{{ emploi.JOBURL }}" target="_blank">{% trans "Apply"%}</a></li>
		</ul>

	</div><!-- div.filterWrap-->
	{% endfor %}
</div><!-- div.outterspace-->
{#% endcache %#}


<div class="row">
<div class="text-left">
<br/>
<!--
                       _             __  _
    ____  ____ _____ _(_)___  ____ _/ /_(_)___  ____
   / __ \/ __ `/ __ `/ / __ \/ __ `/ __/ / __ \/ __ \
  / /_/ / /_/ / /_/ / / / / / /_/ / /_/ / /_/ / / / /
 / .___/\__,_/\__, /_/_/ /_/\__,_/\__/_/\____/_/ /_/
/_/          /____/
-->
 {% bootstrap_paginate page_obj range=5 show_prev_next='true' previous_label='<' next_label='>' last_label='>>' %}
 <!-- end pagination -->
</div>

</div>



	{% endblock %}

applications/emplois/templates/emplois/page_not_found.html
{% extends "base.html" %}
{% load humanize %}
{% load i18n %}

	{% block content %}
  {% get_language_info for LANGUAGE_CODE as lang %}
      {% if lang.code == "en" %}
        <h1>Page not found -- 404</h1>
        <h3>You are trying to find a job that doesn't exist</h3>
        <hr>
    	{% endif %}
    {% if lang.code == "fr" %}
      <h1>Page non trouvé -- 404</h1>
      <h3>Essayez-vous de dénicher un job qui n'existe pas?</h3>
    {% endif %}
 {% endblock  %}

applications/emplois/templates/emplois/result.html
{% extends "base.html" %}
{% load bootstrap_pagination %}
{% load i18n %}
{% load humanize %}


  {% block content %}

  <h1>{% trans "Job list"%}</h1>

<div class="row">
  <div class="col-lg-12">


      {% if keyword %}
        <p><strong>{{ latest_jobs_list|length  }}</strong> {% trans "jobs found for" %} <strong>"{{ keyword }}"</strong></p>

      {% else %}
        <p><strong>{{ latest_jobs_list|length  }}</strong> {% trans "jobs found" %}.</p>
{% endif %}
		</div>
	</div>





<div class="row text-right">
      <ul>
              <li><strong>{% trans "Sort by"%}:</strong></li>
              <li><a href="{% url 'emplois:latest' %}">{% trans "Posted within the last 2 weeks"%}</a></li>
              <li><a href="{% url 'emplois:expire' %}">{% trans "Will expired in 2 weeks from now" %}</a></li>
              <li><a href="{% url 'emplois:all_jobs_posted' %}">{% trans "All jobs" %}</a></li>
      </ul>
	</div>


{#% load cache %#}
{#% cache 500 sidebar %#}


<!--
                       _             __  _
    ____  ____ _____ _(_)___  ____ _/ /_(_)___  ____
   / __ \/ __ `/ __ `/ / __ \/ __ `/ __/ / __ \/ __ \
  / /_/ / /_/ / /_/ / / / / / /_/ / /_/ / /_/ / / / /
 / .___/\__,_/\__, /_/_/ /_/\__,_/\__/_/\____/_/ /_/
/_/          /____/
-->
 {#% bootstrap_paginate page_obj last_label="Last" first_label="First"  range=5 show_prev_next='true' previous_label="<" next_label=">" %#}
 <!-- pagination -->

  {% for emploi in latest_jobs_list %}

          <h3><a href="{% url 'emplois:detail' emploi.id %}">{{ emploi.POSITION }}.</a></h3>
          <p>
  {% autoescape off %}
                        {{ emploi.JOB_SUMMARY |truncatewords_html:50}}.
                  {% endautoescape %}
          </p>
  <ul>
          <li><strong>{% trans "Salary" %}: </strong>
                  {% if ',' in emploi.SALARYMAX %}
          {{ emploi.SALARYMAX | intcomma }}$ {% trans "anually" %}
          {% else %}
          {{ emploi.SALARYMAX | floatformat:2 }}$ {% trans "hourly" %}
          {% endif %}
          </li>
          <li><strong>{% trans "Expiring date"%} : </strong>{{ emploi.EXPIRYDATE }}</li>
          <li><strong>{% trans "postdate" %}: </strong> {{ emploi.POSTDATE| naturalday }}</li>
                <li><strong>{% trans "Apply link" %}: </strong> <a href="{{ emploi.JOBURL }}" target="_blank">{% trans "Apply"%}</a></li>
                <!--
                <li><strong>email it to me: </strong> <a href="#">button</a></li>
                -->
        </ul>

{% endfor %}
{#% endcache %#}


<!--
                       _             __  _
    ____  ____ _____ _(_)___  ____ _/ /_(_)___  ____
   / __ \/ __ `/ __ `/ / __ \/ __ `/ __/ / __ \/ __ \
  / /_/ / /_/ / /_/ / / / / / /_/ / /_/ / /_/ / / / /
 / .___/\__,_/\__, /_/_/ /_/\__,_/\__/_/\____/_/ /_/
/_/          /____/
-->
 {#% bootstrap_paginate page_obj last_label="Last" first_label="First"  range=5 show_prev_next='true' previous_label="<" next_label=">" %#}
 <!-- pagination -->


  {% endblock %}

applications/emplois/templates/emplois/server_error.html
{% extends "base.html" %}
{% load humanize %}
{% load i18n %}

	{% block content %}
  {% get_language_info for LANGUAGE_CODE as lang %}
      {% if lang.code == "en" %}
        <h1>500 -- Server error</h1>
        <h3>Something wrong happends please contact the administrator</h3>
        <hr>
    	{% endif %}
    {% if lang.code == "fr" %}
      <h1>Erreur du serveur -- 500</h1>
      <h3>Veuillez-communiquer avec l'administrateur</h3>
    {% endif %}
 {% endblock  %}